/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Privacy_policyRouteImport } from './routes/privacy_policy'
import { Route as OtogeRouteImport } from './routes/otoge'
import { Route as IndexRouteImport } from './routes/index'

const Privacy_policyRoute = Privacy_policyRouteImport.update({
  id: '/privacy_policy',
  path: '/privacy_policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OtogeRoute = OtogeRouteImport.update({
  id: '/otoge',
  path: '/otoge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/otoge': typeof OtogeRoute
  '/privacy_policy': typeof Privacy_policyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/otoge': typeof OtogeRoute
  '/privacy_policy': typeof Privacy_policyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/otoge': typeof OtogeRoute
  '/privacy_policy': typeof Privacy_policyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/otoge' | '/privacy_policy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/otoge' | '/privacy_policy'
  id: '__root__' | '/' | '/otoge' | '/privacy_policy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OtogeRoute: typeof OtogeRoute
  Privacy_policyRoute: typeof Privacy_policyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy_policy': {
      id: '/privacy_policy'
      path: '/privacy_policy'
      fullPath: '/privacy_policy'
      preLoaderRoute: typeof Privacy_policyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otoge': {
      id: '/otoge'
      path: '/otoge'
      fullPath: '/otoge'
      preLoaderRoute: typeof OtogeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OtogeRoute: OtogeRoute,
  Privacy_policyRoute: Privacy_policyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
