/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Privacy_policyRouteImport } from './routes/privacy_policy'
import { Route as OtogeRouteImport } from './routes/otoge'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevTestWebcamRouteImport } from './routes/dev/test-webcam'
import { Route as DevTestWebAudioApiRouteImport } from './routes/dev/test-web-audio-api'
import { Route as DevTestHandLandmarkerRouteImport } from './routes/dev/test-hand-landmarker'

const Privacy_policyRoute = Privacy_policyRouteImport.update({
  id: '/privacy_policy',
  path: '/privacy_policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OtogeRoute = OtogeRouteImport.update({
  id: '/otoge',
  path: '/otoge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevTestWebcamRoute = DevTestWebcamRouteImport.update({
  id: '/dev/test-webcam',
  path: '/dev/test-webcam',
  getParentRoute: () => rootRouteImport,
} as any)
const DevTestWebAudioApiRoute = DevTestWebAudioApiRouteImport.update({
  id: '/dev/test-web-audio-api',
  path: '/dev/test-web-audio-api',
  getParentRoute: () => rootRouteImport,
} as any)
const DevTestHandLandmarkerRoute = DevTestHandLandmarkerRouteImport.update({
  id: '/dev/test-hand-landmarker',
  path: '/dev/test-hand-landmarker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/otoge': typeof OtogeRoute
  '/privacy_policy': typeof Privacy_policyRoute
  '/dev/test-hand-landmarker': typeof DevTestHandLandmarkerRoute
  '/dev/test-web-audio-api': typeof DevTestWebAudioApiRoute
  '/dev/test-webcam': typeof DevTestWebcamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/otoge': typeof OtogeRoute
  '/privacy_policy': typeof Privacy_policyRoute
  '/dev/test-hand-landmarker': typeof DevTestHandLandmarkerRoute
  '/dev/test-web-audio-api': typeof DevTestWebAudioApiRoute
  '/dev/test-webcam': typeof DevTestWebcamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/otoge': typeof OtogeRoute
  '/privacy_policy': typeof Privacy_policyRoute
  '/dev/test-hand-landmarker': typeof DevTestHandLandmarkerRoute
  '/dev/test-web-audio-api': typeof DevTestWebAudioApiRoute
  '/dev/test-webcam': typeof DevTestWebcamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/otoge'
    | '/privacy_policy'
    | '/dev/test-hand-landmarker'
    | '/dev/test-web-audio-api'
    | '/dev/test-webcam'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/otoge'
    | '/privacy_policy'
    | '/dev/test-hand-landmarker'
    | '/dev/test-web-audio-api'
    | '/dev/test-webcam'
  id:
    | '__root__'
    | '/'
    | '/otoge'
    | '/privacy_policy'
    | '/dev/test-hand-landmarker'
    | '/dev/test-web-audio-api'
    | '/dev/test-webcam'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OtogeRoute: typeof OtogeRoute
  Privacy_policyRoute: typeof Privacy_policyRoute
  DevTestHandLandmarkerRoute: typeof DevTestHandLandmarkerRoute
  DevTestWebAudioApiRoute: typeof DevTestWebAudioApiRoute
  DevTestWebcamRoute: typeof DevTestWebcamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy_policy': {
      id: '/privacy_policy'
      path: '/privacy_policy'
      fullPath: '/privacy_policy'
      preLoaderRoute: typeof Privacy_policyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otoge': {
      id: '/otoge'
      path: '/otoge'
      fullPath: '/otoge'
      preLoaderRoute: typeof OtogeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/test-webcam': {
      id: '/dev/test-webcam'
      path: '/dev/test-webcam'
      fullPath: '/dev/test-webcam'
      preLoaderRoute: typeof DevTestWebcamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/test-web-audio-api': {
      id: '/dev/test-web-audio-api'
      path: '/dev/test-web-audio-api'
      fullPath: '/dev/test-web-audio-api'
      preLoaderRoute: typeof DevTestWebAudioApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/test-hand-landmarker': {
      id: '/dev/test-hand-landmarker'
      path: '/dev/test-hand-landmarker'
      fullPath: '/dev/test-hand-landmarker'
      preLoaderRoute: typeof DevTestHandLandmarkerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OtogeRoute: OtogeRoute,
  Privacy_policyRoute: Privacy_policyRoute,
  DevTestHandLandmarkerRoute: DevTestHandLandmarkerRoute,
  DevTestWebAudioApiRoute: DevTestWebAudioApiRoute,
  DevTestWebcamRoute: DevTestWebcamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
